### ISSUE TITLE
[Errno 2] No such file or directory: 'model/deepmoji_weights.hdf5'

### ISSUE THREAD

**Issue by wanitchayap** [bfelbo/DeepMoji#51] opened 2019-12-10 00:33 UTC
I get this error when I try to run
`python scripts/download_weights.py`

**Comment by bfelbo** [comment] 2020-01-07 17:14
Strange. What's your working directory when running the script?

**Comment by bfelbo** [comment] 2020-01-19 22:46
Closing as I can't reproduce the error. Let me know if you're still facing this issue.

**Closed by bfelbo** 2020-01-19 22:46 UTC

**Comment by tiimoS** [comment] 2020-03-07 16:59
I had a similar issue after deleting the initial model. However, you can still get the file, by downloading it directly using the [dropbox link ](https://www.dropbox.com/s/xqarafsl6a8f9ny/deepmoji_weights.hdf5?dl=0#) and putting it in the ~/model directory.

**Comment by julienbeisel** [comment] 2020-03-14 10:53
same problem on Mac OS, my working directory is the project root
